# Generated by Django 6.0.5 on 2026-06-01 08:09
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0019_alter_course_online_course"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Course",
            new_name="Chapter",
        ),
        migrations.RenameModel(
            old_name="OnlineCourse",
            new_name="Course",
        ),
    ]
