# Generated by Django 6.0.5 on 2026-06-01 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0020_remove_course_online_course_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chapter",
            old_name="online_course",
            new_name="course",
        ),
    ]
