# Generated by Django 6.0.5 on 2026-06-02 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0021_rename_online_course_chapter_course"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Tutor",
        ),
    ]
