# Generated by Django 6.0.5 on 2026-06-03 06:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0024_coursereview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='chpt',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='duration',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
        migrations.AlterField(
            model_name='course',
            name='author',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='course',
            name='language',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
        migrations.AlterField(
            model_name='course',
            name='requirements',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
        migrations.AlterField(
            model_name='coursereview',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='coursereview',
            name='rating',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
