# Generated by Django 6.0.5 on 2026-06-03 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0025_alter_chapter_chpt_alter_chapter_duration_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['chpt']},
        ),
    ]
