# Generated by Django 6.0.5 on 2026-06-15 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0026_alter_chapter_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='duration',
            field=models.PositiveSmallIntegerField(default=200),
        ),
    ]
