# Generated by Django 4.2.1 on 2023-05-16 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_buystudymat_buycourse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='full_address',
        ),
        migrations.AddField(
            model_name='userdetail',
            name='academic_level',
            field=models.CharField(blank=True, choices=[('sec', 'Secondary'), ('hsec', 'Higher Secondary'), ('bch', 'Bachelor'), ('mst', 'Master')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
