# Generated by Django 4.2.1 on 2023-05-23 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0012_studymaterial_file'),
        ('user', '0008_buycourse_pidx_buycourse_total_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=5)),
                ('comment', models.CharField(max_length=1000)),
                ('online_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_course', to='base.onlinecourse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
