# Generated by Django 4.2.1 on 2023-05-23 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_coursereview'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursereview',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
