# Generated by Django 6.0.5 on 2026-06-01 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0020_remove_course_online_course_and_more"),
        ("user", "0010_coursereview_date_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buycourse",
            name="online_course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="buycourse_course",
                to="course.course",
            ),
        ),
        migrations.AlterField(
            model_name="coursereview",
            name="online_course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="review_course",
                to="course.course",
            ),
        ),
    ]
