# Generated by Django 6.0.5 on 2026-06-02 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_coursepurchase_delete_buycourse'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('o', 'Other')], max_length=10)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('academic_level', models.CharField(blank=True, choices=[('sec', 'Secondary'), ('hsec', 'Higher Secondary'), ('bch', 'Bachelor'), ('mst', 'Master')], max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_userprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='UserDetail',
        ),
    ]
