# Generated by Django 6.0.5 on 2026-06-02 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_alter_userprofile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BuyStudyMat',
        ),
    ]
