# Generated by Django 6.0.5 on 2026-06-02 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_delete_buystudymat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CoursePurchase',
        ),
    ]
