# Generated by Django 6.0.5 on 2026-06-02 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_delete_coursepurchase'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseReview',
        ),
    ]
