# Generated by Django 6.0.5 on 2026-06-03 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_delete_coursereview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='academic_level',
            field=models.CharField(choices=[('sec', 'Secondary'), ('hsec', 'Higher Secondary'), ('bch', 'Bachelor'), ('mst', 'Master')], max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.CharField(max_length=500),
        ),
    ]
