# Generated by Django 4.2.1 on 2023-05-15 10:39

import base.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('tech__it', 'Technology and IT'), ('prof_dev', 'Professional Development'), ('creative_arts', 'Creative Arts'), ('health_wellness', 'Health and Wellness'), ('language', 'Language Learning'), ('vocational_trade', 'Vocational and Trade Skills'), ('environmental_studies', 'Environmental Studies'), ('social_sciences', 'Social Sciences'), ('law_studies:', 'Law and Legal Studies:')], max_length=100)),
                ('description', models.CharField(max_length=5000)),
                ('event_date', models.DateTimeField()),
                ('thumbnail', models.ImageField(upload_to=base.models.get_file_path)),
                ('event_venue', models.CharField(max_length=5000)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OnlineCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=5000)),
                ('category', models.CharField(choices=[('tech__it', 'Technology and IT'), ('prof_dev', 'Professional Development'), ('creative_arts', 'Creative Arts'), ('health_wellness', 'Health and Wellness'), ('language', 'Language Learning'), ('vocational_trade', 'Vocational and Trade Skills'), ('environmental_studies', 'Environmental Studies'), ('social_sciences', 'Social Sciences'), ('law_studies:', 'Law and Legal Studies:')], max_length=100)),
                ('syllabus', models.CharField(max_length=5000)),
                ('thumbnail', models.ImageField(upload_to=base.models.get_file_path)),
                ('preview_video', models.FileField(upload_to=base.models.get_file_path)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('price', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='StudyMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('tech__it', 'Technology and IT'), ('prof_dev', 'Professional Development'), ('creative_arts', 'Creative Arts'), ('health_wellness', 'Health and Wellness'), ('language', 'Language Learning'), ('vocational_trade', 'Vocational and Trade Skills'), ('environmental_studies', 'Environmental Studies'), ('social_sciences', 'Social Sciences'), ('law_studies:', 'Law and Legal Studies:')], max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=5000)),
                ('thumbnail', models.ImageField(upload_to=base.models.get_file_path)),
                ('preview_video', models.FileField(upload_to=base.models.get_file_path)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('price', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('o', 'Other')], max_length=10)),
                ('full_address', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userdetail_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=5000)),
                ('video', models.FileField(upload_to=base.models.get_file_path)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('duration', models.IntegerField(default=1)),
                ('online_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_onlinecourse', to='base.onlinecourse')),
            ],
        ),
        migrations.CreateModel(
            name='BuyStudyMat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('study_mat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buystudymat_studymat', to='base.studymaterial')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buystudymat_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BuyCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('online_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buycourse_course', to='base.onlinecourse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buycourse_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
