# Generated by Django 4.2.1 on 2023-05-15 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_course_chpt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('tech_it', 'Technology and IT'), ('prof_dev', 'Professional Development'), ('creative_arts', 'Creative Arts'), ('health_wellness', 'Health and Wellness'), ('language', 'Language Learning'), ('vocational_trade', 'Vocational and Trade Skills'), ('environmental_studies', 'Environmental Studies'), ('social_sciences', 'Social Sciences'), ('law_studies:', 'Law and Legal Studies:')], max_length=100),
        ),
        migrations.AlterField(
            model_name='onlinecourse',
            name='category',
            field=models.CharField(choices=[('tech_it', 'Technology and IT'), ('prof_dev', 'Professional Development'), ('creative_arts', 'Creative Arts'), ('health_wellness', 'Health and Wellness'), ('language', 'Language Learning'), ('vocational_trade', 'Vocational and Trade Skills'), ('environmental_studies', 'Environmental Studies'), ('social_sciences', 'Social Sciences'), ('law_studies:', 'Law and Legal Studies:')], max_length=100),
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='category',
            field=models.CharField(choices=[('tech_it', 'Technology and IT'), ('prof_dev', 'Professional Development'), ('creative_arts', 'Creative Arts'), ('health_wellness', 'Health and Wellness'), ('language', 'Language Learning'), ('vocational_trade', 'Vocational and Trade Skills'), ('environmental_studies', 'Environmental Studies'), ('social_sciences', 'Social Sciences'), ('law_studies:', 'Law and Legal Studies:')], max_length=100),
        ),
    ]
