# Generated by Django 4.2.1 on 2023-05-15 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_event_category_alter_onlinecourse_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buystudymat',
            name='study_mat',
        ),
        migrations.RemoveField(
            model_name='buystudymat',
            name='user',
        ),
        migrations.DeleteModel(
            name='BuyCourse',
        ),
        migrations.DeleteModel(
            name='BuyStudyMat',
        ),
    ]
