# Generated by Django 4.2.1 on 2023-05-20 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_course_slug_event_slug_onlinecourse_slug_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studymaterial',
            old_name='preview_video',
            new_name='file',
        ),
    ]
