# Generated by Django 4.2.1 on 2023-05-20 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_rename_preview_video_studymaterial_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studymaterial',
            name='file',
        ),
    ]
