# Generated by Django 4.2.1 on 2023-05-20 12:10

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_remove_studymaterial_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymaterial',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=base.models.get_file_path),
        ),
    ]
