# Generated by Django 4.2.1 on 2023-05-24 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_onlinecourse_avg_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinecourse',
            name='avg_rating',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
