# Generated by Django 4.2.1 on 2023-06-04 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_onlinecourse_avg_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onlinecourse',
            name='avg_rating',
        ),
    ]
