# Generated by Django 3.2.20 on 2024-10-29 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_remove_onlinecourse_avg_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='online_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_chapters', to='base.onlinecourse'),
        ),
    ]
