# Generated by Django 6.0.5 on 2026-06-02 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0023_delete_event_delete_studymaterial_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursePurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('pidx', models.CharField(blank=True, max_length=24, null=True)),
                ('total_amount', models.IntegerField(blank=True, default=1000, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=24, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_coursepurchases', to='course.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_coursepurchases', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
