# Generated by Django 6.0.5 on 2026-06-03 06:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursepurchase',
            name='pidx',
            field=models.CharField(max_length=24),
        ),
        migrations.AlterField(
            model_name='coursepurchase',
            name='total_amount',
            field=models.FloatField(default=1000, validators=[django.core.validators.MinValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='coursepurchase',
            name='transaction_id',
            field=models.CharField(max_length=24),
        ),
    ]
